name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image  # Step 6: 어플리케이션용 Docker 이미지 빌드
      run: |
        docker build . -t ${{ secrets.DOCKER_USERNAME }}/korean-quote:${{ github.sha }}  # GitHub SHA로 태그한 Docker 이미지 빌드
        docker tag ${{ secrets.DOCKER_USERNAME }}/korean-quote:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/korean-quote:latest  # Docker 이미지를 'latest'로 태그

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        ssh ${SERVER_USER}@${SERVER_IP} << 'EOF'
          docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
          docker pull ${DOCKER_USERNAME}/korean-quote:latest
          docker stop korean-quote || true
          docker rm korean-quote || true
          docker run -d --name korean-quote -p 3000:3000 ${DOCKER_USERNAME}/korean-quote:latest
        EOF
